#!/bin/bash
# ==========================================================
# Script 5: Open Source Manifesto Generator
# Author: Naina Yadav
# Course: Open Source Software
# Description: Generates a personalized open source manifesto
# ==========================================================

echo "=============================================="
echo "   Open Source Manifesto Generator"
echo "=============================================="
echo "Answer three questions to generate your manifesto."
echo ""

# -------- User Input --------
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# -------- Date and Output File --------
DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# -------- Generate Manifesto --------
echo "" > $OUTPUT
echo "Open Source Manifesto" >> $OUTPUT
echo "Date: $DATE" >> $OUTPUT
echo "" >> $OUTPUT

echo "I believe in the power of open source software." >> $OUTPUT
echo "Using tools like $TOOL, I experience the true meaning of $FREEDOM." >> $OUTPUT
echo "I believe knowledge should be shared, not restricted." >> $OUTPUT
echo "In the future, I aim to build and share $BUILD with the world." >> $OUTPUT
echo "Open source is not just code — it is a philosophy of collaboration and innovation." >> $OUTPUT

echo "" >> $OUTPUT
echo "— Generated by $(whoami)" >> $OUTPUT

# -------- Display Output --------
echo ""
echo "Manifesto saved to $OUTPUT"
echo "----------------------------------------------"
cat $OUTPUT

# -------- Alias Concept (for demonstration) --------
# Example: You can create an alias like:
# alias manifesto='./script5.sh'
# Then just type 'manifesto' to run this script quickly
